# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ObjectiveCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'MarkelyticsSurvey', '1.0.0'


  # Pods for ObjectiveCDemo

  target 'ObjectiveCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjectiveCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
