# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MarkelyticsSurvey', '1.0.0'

  # Pods for SwiftDemo

  target 'SwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
